// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm_entry.proto

package com.mogujie.jarvis.protocol;

public final class AlarmEntryProtos {
    private AlarmEntryProtos() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface AlarmEntryOrBuilder extends
            // @@protoc_insertion_point(interface_extends:AlarmEntry)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 id = 3;</code>
         */
        boolean hasId();

        /**
         * <code>required int32 id = 3;</code>
         */
        int getId();

        /**
         * <code>required int64 job_id = 4;</code>
         */
        boolean hasJobId();

        /**
         * <code>required int64 job_id = 4;</code>
         */
        long getJobId();

        /**
         * <code>required string alarmType = 5;</code>
         */
        boolean hasAlarmType();

        /**
         * <code>required string alarmType = 5;</code>
         */
        java.lang.String getAlarmType();

        /**
         * <code>required string alarmType = 5;</code>
         */
        com.google.protobuf.ByteString getAlarmTypeBytes();

        /**
         * <code>required string reciever = 6;</code>
         */
        boolean hasReciever();

        /**
         * <code>required string reciever = 6;</code>
         */
        java.lang.String getReciever();

        /**
         * <code>required string reciever = 6;</code>
         */
        com.google.protobuf.ByteString getRecieverBytes();

        /**
         * <code>required int32 status = 7;</code>
         */
        boolean hasStatus();

        /**
         * <code>required int32 status = 7;</code>
         */
        int getStatus();
    }

    /**
     * Protobuf type {@code AlarmEntry}
     */
    public static final class AlarmEntry extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:AlarmEntry)
            AlarmEntryOrBuilder {
        // Use AlarmEntry.newBuilder() to construct.
        private AlarmEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private AlarmEntry(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final AlarmEntry defaultInstance;

        public static AlarmEntry getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public AlarmEntry getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private AlarmEntry(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readInt32();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000002;
                            jobId_ = input.readInt64();
                            break;
                        }
                        case 42: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            alarmType_ = bs;
                            break;
                        }
                        case 50: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000008;
                            reciever_ = bs;
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000010;
                            status_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.AlarmEntryProtos.internal_static_AlarmEntry_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.AlarmEntryProtos.internal_static_AlarmEntry_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry.class,
                    com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry.Builder.class);
        }

        public static com.google.protobuf.Parser<AlarmEntry> PARSER = new com.google.protobuf.AbstractParser<AlarmEntry>() {
            @Override
            public AlarmEntry parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new AlarmEntry(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<AlarmEntry> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 3;
        private int id_;

        /**
         * <code>required int32 id = 3;</code>
         */
        @Override
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 id = 3;</code>
         */
        @Override
        public int getId() {
            return id_;
        }

        public static final int JOB_ID_FIELD_NUMBER = 4;
        private long jobId_;

        /**
         * <code>required int64 job_id = 4;</code>
         */
        @Override
        public boolean hasJobId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int64 job_id = 4;</code>
         */
        @Override
        public long getJobId() {
            return jobId_;
        }

        public static final int ALARMTYPE_FIELD_NUMBER = 5;
        private java.lang.Object alarmType_;

        /**
         * <code>required string alarmType = 5;</code>
         */
        @Override
        public boolean hasAlarmType() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string alarmType = 5;</code>
         */
        @Override
        public java.lang.String getAlarmType() {
            java.lang.Object ref = alarmType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    alarmType_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string alarmType = 5;</code>
         */
        @Override
        public com.google.protobuf.ByteString getAlarmTypeBytes() {
            java.lang.Object ref = alarmType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                alarmType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int RECIEVER_FIELD_NUMBER = 6;
        private java.lang.Object reciever_;

        /**
         * <code>required string reciever = 6;</code>
         */
        @Override
        public boolean hasReciever() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required string reciever = 6;</code>
         */
        @Override
        public java.lang.String getReciever() {
            java.lang.Object ref = reciever_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    reciever_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string reciever = 6;</code>
         */
        @Override
        public com.google.protobuf.ByteString getRecieverBytes() {
            java.lang.Object ref = reciever_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                reciever_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int STATUS_FIELD_NUMBER = 7;
        private int status_;

        /**
         * <code>required int32 status = 7;</code>
         */
        @Override
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>required int32 status = 7;</code>
         */
        @Override
        public int getStatus() {
            return status_;
        }

        private void initFields() {
            id_ = 0;
            jobId_ = 0L;
            alarmType_ = "";
            reciever_ = "";
            status_ = 0;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasJobId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAlarmType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasReciever()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasStatus()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(3, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(4, jobId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(5, getAlarmTypeBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(6, getRecieverBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt32(7, status_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, jobId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(5, getAlarmTypeBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(6, getRecieverBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(7, status_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code AlarmEntry}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:AlarmEntry)
                com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.AlarmEntryProtos.internal_static_AlarmEntry_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.AlarmEntryProtos.internal_static_AlarmEntry_fieldAccessorTable.ensureFieldAccessorsInitialized(
                        com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry.class,
                        com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry.Builder.class);
            }

            // Construct using com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                id_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                jobId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                alarmType_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                reciever_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                status_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.AlarmEntryProtos.internal_static_AlarmEntry_descriptor;
            }

            @Override
            public com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry.getDefaultInstance();
            }

            @Override
            public com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry build() {
                com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry buildPartial() {
                com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry result = new com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.jobId_ = jobId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.alarmType_ = alarmType_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.reciever_ = reciever_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.status_ = status_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry) {
                    return mergeFrom((com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry other) {
                if (other == com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry.getDefaultInstance())
                    return this;
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasJobId()) {
                    setJobId(other.getJobId());
                }
                if (other.hasAlarmType()) {
                    bitField0_ |= 0x00000004;
                    alarmType_ = other.alarmType_;
                    onChanged();
                }
                if (other.hasReciever()) {
                    bitField0_ |= 0x00000008;
                    reciever_ = other.reciever_;
                    onChanged();
                }
                if (other.hasStatus()) {
                    setStatus(other.getStatus());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasId()) {

                    return false;
                }
                if (!hasJobId()) {

                    return false;
                }
                if (!hasAlarmType()) {

                    return false;
                }
                if (!hasReciever()) {

                    return false;
                }
                if (!hasStatus()) {

                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.AlarmEntryProtos.AlarmEntry) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int id_;

            /**
             * <code>required int32 id = 3;</code>
             */
            @Override
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 id = 3;</code>
             */
            @Override
            public int getId() {
                return id_;
            }

            /**
             * <code>required int32 id = 3;</code>
             */
            public Builder setId(int value) {
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 id = 3;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                onChanged();
                return this;
            }

            private long jobId_;

            /**
             * <code>required int64 job_id = 4;</code>
             */
            @Override
            public boolean hasJobId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int64 job_id = 4;</code>
             */
            @Override
            public long getJobId() {
                return jobId_;
            }

            /**
             * <code>required int64 job_id = 4;</code>
             */
            public Builder setJobId(long value) {
                bitField0_ |= 0x00000002;
                jobId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 job_id = 4;</code>
             */
            public Builder clearJobId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                jobId_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object alarmType_ = "";

            /**
             * <code>required string alarmType = 5;</code>
             */
            @Override
            public boolean hasAlarmType() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string alarmType = 5;</code>
             */
            @Override
            public java.lang.String getAlarmType() {
                java.lang.Object ref = alarmType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        alarmType_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string alarmType = 5;</code>
             */
            @Override
            public com.google.protobuf.ByteString getAlarmTypeBytes() {
                java.lang.Object ref = alarmType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    alarmType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string alarmType = 5;</code>
             */
            public Builder setAlarmType(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                alarmType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string alarmType = 5;</code>
             */
            public Builder clearAlarmType() {
                bitField0_ = (bitField0_ & ~0x00000004);
                alarmType_ = getDefaultInstance().getAlarmType();
                onChanged();
                return this;
            }

            /**
             * <code>required string alarmType = 5;</code>
             */
            public Builder setAlarmTypeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                alarmType_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object reciever_ = "";

            /**
             * <code>required string reciever = 6;</code>
             */
            @Override
            public boolean hasReciever() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>required string reciever = 6;</code>
             */
            @Override
            public java.lang.String getReciever() {
                java.lang.Object ref = reciever_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        reciever_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string reciever = 6;</code>
             */
            @Override
            public com.google.protobuf.ByteString getRecieverBytes() {
                java.lang.Object ref = reciever_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    reciever_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string reciever = 6;</code>
             */
            public Builder setReciever(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                reciever_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string reciever = 6;</code>
             */
            public Builder clearReciever() {
                bitField0_ = (bitField0_ & ~0x00000008);
                reciever_ = getDefaultInstance().getReciever();
                onChanged();
                return this;
            }

            /**
             * <code>required string reciever = 6;</code>
             */
            public Builder setRecieverBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                reciever_ = value;
                onChanged();
                return this;
            }

            private int status_;

            /**
             * <code>required int32 status = 7;</code>
             */
            @Override
            public boolean hasStatus() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>required int32 status = 7;</code>
             */
            @Override
            public int getStatus() {
                return status_;
            }

            /**
             * <code>required int32 status = 7;</code>
             */
            public Builder setStatus(int value) {
                bitField0_ |= 0x00000010;
                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 status = 7;</code>
             */
            public Builder clearStatus() {
                bitField0_ = (bitField0_ & ~0x00000010);
                status_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:AlarmEntry)
        }

        static {
            defaultInstance = new AlarmEntry(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:AlarmEntry)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_AlarmEntry_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_AlarmEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\021alarm_entry.proto\"]\n\nAlarmEntry\022\n\n\002id\030"
                + "\003 \002(\005\022\016\n\006job_id\030\004 \002(\003\022\021\n\talarmType\030\005 \002(\t"
                + "\022\020\n\010reciever\030\006 \002(\t\022\016\n\006status\030\007 \002(\005B/\n\033co"
                + "m.mogujie.jarvis.protocolB\020AlarmEntryPro" + "tos" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            @Override
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_AlarmEntry_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_AlarmEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_AlarmEntry_descriptor, new java.lang.String[] { "Id", "JobId", "AlarmType", "Reciever", "Status", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
