// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_task_status.proto

package com.mogujie.jarvis.protocol;

public final class QueryTaskStatusProtos {
    private QueryTaskStatusProtos() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface RestServerQueryTaskStatusRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RestServerQueryTaskStatusRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        boolean hasAppAuth();

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth();

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder();

        /**
         * <code>required int64 task_id = 2;</code>
         */
        boolean hasTaskId();

        /**
         * <code>required int64 task_id = 2;</code>
         */
        long getTaskId();
    }

    /**
     * Protobuf type {@code RestServerQueryTaskStatusRequest}
     */
    public static final class RestServerQueryTaskStatusRequest extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:RestServerQueryTaskStatusRequest)
            RestServerQueryTaskStatusRequestOrBuilder {
        // Use RestServerQueryTaskStatusRequest.newBuilder() to construct.
        private RestServerQueryTaskStatusRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private RestServerQueryTaskStatusRequest(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final RestServerQueryTaskStatusRequest defaultInstance;

        public static RestServerQueryTaskStatusRequest getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public RestServerQueryTaskStatusRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private RestServerQueryTaskStatusRequest(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                                subBuilder = appAuth_.toBuilder();
                            }
                            appAuth_ = input.readMessage(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(appAuth_);
                                appAuth_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            taskId_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_RestServerQueryTaskStatusRequest_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_RestServerQueryTaskStatusRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest.class,
                            com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest.Builder.class);
        }

        public static com.google.protobuf.Parser<RestServerQueryTaskStatusRequest> PARSER = new com.google.protobuf.AbstractParser<RestServerQueryTaskStatusRequest>() {
            @Override
            public RestServerQueryTaskStatusRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new RestServerQueryTaskStatusRequest(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<RestServerQueryTaskStatusRequest> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int APP_AUTH_FIELD_NUMBER = 1;
        private com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth appAuth_;

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        @Override
        public boolean hasAppAuth() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        @Override
        public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth() {
            return appAuth_;
        }

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        @Override
        public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder() {
            return appAuth_;
        }

        public static final int TASK_ID_FIELD_NUMBER = 2;
        private long taskId_;

        /**
         * <code>required int64 task_id = 2;</code>
         */
        @Override
        public boolean hasTaskId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int64 task_id = 2;</code>
         */
        @Override
        public long getTaskId() {
            return taskId_;
        }

        private void initFields() {
            appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
            taskId_ = 0L;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasAppAuth()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTaskId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!getAppAuth().isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeMessage(1, appAuth_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, taskId_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, appAuth_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, taskId_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code RestServerQueryTaskStatusRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RestServerQueryTaskStatusRequest)
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_RestServerQueryTaskStatusRequest_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_RestServerQueryTaskStatusRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest.class,
                                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest.Builder.class);
            }

            // Construct using com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getAppAuthFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                if (appAuthBuilder_ == null) {
                    appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
                } else {
                    appAuthBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                taskId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_RestServerQueryTaskStatusRequest_descriptor;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest.getDefaultInstance();
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest build() {
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest buildPartial() {
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest result = new com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                if (appAuthBuilder_ == null) {
                    result.appAuth_ = appAuth_;
                } else {
                    result.appAuth_ = appAuthBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.taskId_ = taskId_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest) {
                    return mergeFrom((com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest other) {
                if (other == com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest.getDefaultInstance())
                    return this;
                if (other.hasAppAuth()) {
                    mergeAppAuth(other.getAppAuth());
                }
                if (other.hasTaskId()) {
                    setTaskId(other.getTaskId());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasAppAuth()) {

                    return false;
                }
                if (!hasTaskId()) {

                    return false;
                }
                if (!getAppAuth().isInitialized()) {

                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.QueryTaskStatusProtos.RestServerQueryTaskStatusRequest) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth
                    .getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder> appAuthBuilder_;

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            @Override
            public boolean hasAppAuth() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            @Override
            public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth() {
                if (appAuthBuilder_ == null) {
                    return appAuth_;
                } else {
                    return appAuthBuilder_.getMessage();
                }
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder setAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth value) {
                if (appAuthBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    appAuth_ = value;
                    onChanged();
                } else {
                    appAuthBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder setAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder builderForValue) {
                if (appAuthBuilder_ == null) {
                    appAuth_ = builderForValue.build();
                    onChanged();
                } else {
                    appAuthBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder mergeAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth value) {
                if (appAuthBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)
                            && appAuth_ != com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance()) {
                        appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.newBuilder(appAuth_).mergeFrom(value).buildPartial();
                    } else {
                        appAuth_ = value;
                    }
                    onChanged();
                } else {
                    appAuthBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder clearAppAuth() {
                if (appAuthBuilder_ == null) {
                    appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
                    onChanged();
                } else {
                    appAuthBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder getAppAuthBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getAppAuthFieldBuilder().getBuilder();
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            @Override
            public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder() {
                if (appAuthBuilder_ != null) {
                    return appAuthBuilder_.getMessageOrBuilder();
                } else {
                    return appAuth_;
                }
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder> getAppAuthFieldBuilder() {
                if (appAuthBuilder_ == null) {
                    appAuthBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder>(
                            getAppAuth(), getParentForChildren(), isClean());
                    appAuth_ = null;
                }
                return appAuthBuilder_;
            }

            private long taskId_;

            /**
             * <code>required int64 task_id = 2;</code>
             */
            @Override
            public boolean hasTaskId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int64 task_id = 2;</code>
             */
            @Override
            public long getTaskId() {
                return taskId_;
            }

            /**
             * <code>required int64 task_id = 2;</code>
             */
            public Builder setTaskId(long value) {
                bitField0_ |= 0x00000002;
                taskId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 task_id = 2;</code>
             */
            public Builder clearTaskId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                taskId_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:RestServerQueryTaskStatusRequest)
        }

        static {
            defaultInstance = new RestServerQueryTaskStatusRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:RestServerQueryTaskStatusRequest)
    }

    public interface ServerQueryTaskStatusResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ServerQueryTaskStatusResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bool success = 1;</code>
         */
        boolean hasSuccess();

        /**
         * <code>required bool success = 1;</code>
         */
        boolean getSuccess();

        /**
         * <code>optional int32 status = 2;</code>
         */
        boolean hasStatus();

        /**
         * <code>optional int32 status = 2;</code>
         */
        int getStatus();

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        boolean hasMessage();

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        java.lang.String getMessage();

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        com.google.protobuf.ByteString getMessageBytes();
    }

    /**
     * Protobuf type {@code ServerQueryTaskStatusResponse}
     */
    public static final class ServerQueryTaskStatusResponse extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:ServerQueryTaskStatusResponse)
            ServerQueryTaskStatusResponseOrBuilder {
        // Use ServerQueryTaskStatusResponse.newBuilder() to construct.
        private ServerQueryTaskStatusResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private ServerQueryTaskStatusResponse(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final ServerQueryTaskStatusResponse defaultInstance;

        public static ServerQueryTaskStatusResponse getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public ServerQueryTaskStatusResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private ServerQueryTaskStatusResponse(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            success_ = input.readBool();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            status_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            message_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_ServerQueryTaskStatusResponse_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_ServerQueryTaskStatusResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse.class,
                            com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse.Builder.class);
        }

        public static com.google.protobuf.Parser<ServerQueryTaskStatusResponse> PARSER = new com.google.protobuf.AbstractParser<ServerQueryTaskStatusResponse>() {
            @Override
            public ServerQueryTaskStatusResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new ServerQueryTaskStatusResponse(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<ServerQueryTaskStatusResponse> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int SUCCESS_FIELD_NUMBER = 1;
        private boolean success_;

        /**
         * <code>required bool success = 1;</code>
         */
        @Override
        public boolean hasSuccess() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bool success = 1;</code>
         */
        @Override
        public boolean getSuccess() {
            return success_;
        }

        public static final int STATUS_FIELD_NUMBER = 2;
        private int status_;

        /**
         * <code>optional int32 status = 2;</code>
         */
        @Override
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int32 status = 2;</code>
         */
        @Override
        public int getStatus() {
            return status_;
        }

        public static final int MESSAGE_FIELD_NUMBER = 3;
        private java.lang.Object message_;

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        @Override
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        @Override
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        @Override
        public com.google.protobuf.ByteString getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            success_ = false;
            status_ = 0;
            message_ = "";
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasSuccess()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBool(1, success_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, status_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(1, success_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, status_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ServerQueryTaskStatusResponse}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ServerQueryTaskStatusResponse)
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_ServerQueryTaskStatusResponse_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_ServerQueryTaskStatusResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse.class,
                                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse.Builder.class);
            }

            // Construct using com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                success_ = false;
                bitField0_ = (bitField0_ & ~0x00000001);
                status_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.internal_static_ServerQueryTaskStatusResponse_descriptor;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse.getDefaultInstance();
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse build() {
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse buildPartial() {
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse result = new com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.success_ = success_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.status_ = status_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse) {
                    return mergeFrom((com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse other) {
                if (other == com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse.getDefaultInstance())
                    return this;
                if (other.hasSuccess()) {
                    setSuccess(other.getSuccess());
                }
                if (other.hasStatus()) {
                    setStatus(other.getStatus());
                }
                if (other.hasMessage()) {
                    bitField0_ |= 0x00000004;
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasSuccess()) {

                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.QueryTaskStatusProtos.ServerQueryTaskStatusResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private boolean success_;

            /**
             * <code>required bool success = 1;</code>
             */
            @Override
            public boolean hasSuccess() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bool success = 1;</code>
             */
            @Override
            public boolean getSuccess() {
                return success_;
            }

            /**
             * <code>required bool success = 1;</code>
             */
            public Builder setSuccess(boolean value) {
                bitField0_ |= 0x00000001;
                success_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bool success = 1;</code>
             */
            public Builder clearSuccess() {
                bitField0_ = (bitField0_ & ~0x00000001);
                success_ = false;
                onChanged();
                return this;
            }

            private int status_;

            /**
             * <code>optional int32 status = 2;</code>
             */
            @Override
            public boolean hasStatus() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int32 status = 2;</code>
             */
            @Override
            public int getStatus() {
                return status_;
            }

            /**
             * <code>optional int32 status = 2;</code>
             */
            public Builder setStatus(int value) {
                bitField0_ |= 0x00000002;
                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 status = 2;</code>
             */
            public Builder clearStatus() {
                bitField0_ = (bitField0_ & ~0x00000002);
                status_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object message_ = "";

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            @Override
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            @Override
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        message_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            @Override
            public com.google.protobuf.ByteString getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            public Builder setMessage(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000004);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            public Builder setMessageBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ServerQueryTaskStatusResponse)
        }

        static {
            defaultInstance = new ServerQueryTaskStatusResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:ServerQueryTaskStatusResponse)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_RestServerQueryTaskStatusRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_RestServerQueryTaskStatusRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_ServerQueryTaskStatusResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_ServerQueryTaskStatusResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\027query_task_status.proto\032\016app_auth.prot" + "o\"O\n RestServerQueryTaskStatusRequest\022\032\n"
                        + "\010app_auth\030\001 \002(\0132\010.AppAuth\022\017\n\007task_id\030\002 \002"
                        + "(\003\"S\n\035ServerQueryTaskStatusResponse\022\017\n\007s"
                        + "uccess\030\001 \002(\010\022\016\n\006status\030\002 \001(\005\022\021\n\007message\030"
                        + "\003 \001(\t:\000B4\n\033com.mogujie.jarvis.protocolB\025" + "QueryTaskStatusProtos" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            @Override
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] { com.mogujie.jarvis.protocol.AppAuthProtos.getDescriptor(), }, assigner);
        internal_static_RestServerQueryTaskStatusRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_RestServerQueryTaskStatusRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_RestServerQueryTaskStatusRequest_descriptor, new java.lang.String[] { "AppAuth", "TaskId", });
        internal_static_ServerQueryTaskStatusResponse_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_ServerQueryTaskStatusResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ServerQueryTaskStatusResponse_descriptor, new java.lang.String[] { "Success", "Status", "Message", });
        com.mogujie.jarvis.protocol.AppAuthProtos.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
