// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_task.proto

package com.mogujie.jarvis.protocol;

public final class QueryTaskProtos {
    private QueryTaskProtos() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface RestQueryTaskCriticalPathRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RestQueryTaskCriticalPathRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        boolean hasAppAuth();

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth();

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder();

        /**
         * <code>required int64 date_time = 2;</code>
         */
        boolean hasDateTime();

        /**
         * <code>required int64 date_time = 2;</code>
         */
        long getDateTime();

        /**
         * <code>required string job_name = 3;</code>
         */
        boolean hasJobName();

        /**
         * <code>required string job_name = 3;</code>
         */
        java.lang.String getJobName();

        /**
         * <code>required string job_name = 3;</code>
         */
        com.google.protobuf.ByteString getJobNameBytes();
    }

    /**
     * Protobuf type {@code RestQueryTaskCriticalPathRequest}
     */
    public static final class RestQueryTaskCriticalPathRequest extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:RestQueryTaskCriticalPathRequest)
            RestQueryTaskCriticalPathRequestOrBuilder {
        // Use RestQueryTaskCriticalPathRequest.newBuilder() to construct.
        private RestQueryTaskCriticalPathRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private RestQueryTaskCriticalPathRequest(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final RestQueryTaskCriticalPathRequest defaultInstance;

        public static RestQueryTaskCriticalPathRequest getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public RestQueryTaskCriticalPathRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private RestQueryTaskCriticalPathRequest(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                                subBuilder = appAuth_.toBuilder();
                            }
                            appAuth_ = input.readMessage(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(appAuth_);
                                appAuth_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            dateTime_ = input.readInt64();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            jobName_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_RestQueryTaskCriticalPathRequest_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_RestQueryTaskCriticalPathRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest.class,
                            com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest.Builder.class);
        }

        public static com.google.protobuf.Parser<RestQueryTaskCriticalPathRequest> PARSER = new com.google.protobuf.AbstractParser<RestQueryTaskCriticalPathRequest>() {
            @Override
            public RestQueryTaskCriticalPathRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new RestQueryTaskCriticalPathRequest(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<RestQueryTaskCriticalPathRequest> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int APP_AUTH_FIELD_NUMBER = 1;
        private com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth appAuth_;

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        @Override
        public boolean hasAppAuth() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        @Override
        public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth() {
            return appAuth_;
        }

        /**
         * <code>required .AppAuth app_auth = 1;</code>
         */
        @Override
        public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder() {
            return appAuth_;
        }

        public static final int DATE_TIME_FIELD_NUMBER = 2;
        private long dateTime_;

        /**
         * <code>required int64 date_time = 2;</code>
         */
        @Override
        public boolean hasDateTime() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int64 date_time = 2;</code>
         */
        @Override
        public long getDateTime() {
            return dateTime_;
        }

        public static final int JOB_NAME_FIELD_NUMBER = 3;
        private java.lang.Object jobName_;

        /**
         * <code>required string job_name = 3;</code>
         */
        @Override
        public boolean hasJobName() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string job_name = 3;</code>
         */
        @Override
        public java.lang.String getJobName() {
            java.lang.Object ref = jobName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    jobName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string job_name = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString getJobNameBytes() {
            java.lang.Object ref = jobName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                jobName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
            dateTime_ = 0L;
            jobName_ = "";
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasAppAuth()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDateTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasJobName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!getAppAuth().isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeMessage(1, appAuth_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, dateTime_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getJobNameBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, appAuth_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, dateTime_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getJobNameBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code RestQueryTaskCriticalPathRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RestQueryTaskCriticalPathRequest)
                com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_RestQueryTaskCriticalPathRequest_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_RestQueryTaskCriticalPathRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest.class,
                                com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest.Builder.class);
            }

            // Construct using com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getAppAuthFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                if (appAuthBuilder_ == null) {
                    appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
                } else {
                    appAuthBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                dateTime_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                jobName_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_RestQueryTaskCriticalPathRequest_descriptor;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest.getDefaultInstance();
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest build() {
                com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest buildPartial() {
                com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest result = new com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                if (appAuthBuilder_ == null) {
                    result.appAuth_ = appAuth_;
                } else {
                    result.appAuth_ = appAuthBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.dateTime_ = dateTime_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.jobName_ = jobName_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest) {
                    return mergeFrom((com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest other) {
                if (other == com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest.getDefaultInstance())
                    return this;
                if (other.hasAppAuth()) {
                    mergeAppAuth(other.getAppAuth());
                }
                if (other.hasDateTime()) {
                    setDateTime(other.getDateTime());
                }
                if (other.hasJobName()) {
                    bitField0_ |= 0x00000004;
                    jobName_ = other.jobName_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasAppAuth()) {

                    return false;
                }
                if (!hasDateTime()) {

                    return false;
                }
                if (!hasJobName()) {

                    return false;
                }
                if (!getAppAuth().isInitialized()) {

                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.QueryTaskProtos.RestQueryTaskCriticalPathRequest) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth
                    .getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder> appAuthBuilder_;

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            @Override
            public boolean hasAppAuth() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            @Override
            public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth() {
                if (appAuthBuilder_ == null) {
                    return appAuth_;
                } else {
                    return appAuthBuilder_.getMessage();
                }
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder setAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth value) {
                if (appAuthBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    appAuth_ = value;
                    onChanged();
                } else {
                    appAuthBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder setAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder builderForValue) {
                if (appAuthBuilder_ == null) {
                    appAuth_ = builderForValue.build();
                    onChanged();
                } else {
                    appAuthBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder mergeAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth value) {
                if (appAuthBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)
                            && appAuth_ != com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance()) {
                        appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.newBuilder(appAuth_).mergeFrom(value).buildPartial();
                    } else {
                        appAuth_ = value;
                    }
                    onChanged();
                } else {
                    appAuthBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public Builder clearAppAuth() {
                if (appAuthBuilder_ == null) {
                    appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
                    onChanged();
                } else {
                    appAuthBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder getAppAuthBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getAppAuthFieldBuilder().getBuilder();
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            @Override
            public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder() {
                if (appAuthBuilder_ != null) {
                    return appAuthBuilder_.getMessageOrBuilder();
                } else {
                    return appAuth_;
                }
            }

            /**
             * <code>required .AppAuth app_auth = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder> getAppAuthFieldBuilder() {
                if (appAuthBuilder_ == null) {
                    appAuthBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder>(
                            getAppAuth(), getParentForChildren(), isClean());
                    appAuth_ = null;
                }
                return appAuthBuilder_;
            }

            private long dateTime_;

            /**
             * <code>required int64 date_time = 2;</code>
             */
            @Override
            public boolean hasDateTime() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int64 date_time = 2;</code>
             */
            @Override
            public long getDateTime() {
                return dateTime_;
            }

            /**
             * <code>required int64 date_time = 2;</code>
             */
            public Builder setDateTime(long value) {
                bitField0_ |= 0x00000002;
                dateTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 date_time = 2;</code>
             */
            public Builder clearDateTime() {
                bitField0_ = (bitField0_ & ~0x00000002);
                dateTime_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object jobName_ = "";

            /**
             * <code>required string job_name = 3;</code>
             */
            @Override
            public boolean hasJobName() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            @Override
            public java.lang.String getJobName() {
                java.lang.Object ref = jobName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        jobName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            @Override
            public com.google.protobuf.ByteString getJobNameBytes() {
                java.lang.Object ref = jobName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    jobName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            public Builder setJobName(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                jobName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            public Builder clearJobName() {
                bitField0_ = (bitField0_ & ~0x00000004);
                jobName_ = getDefaultInstance().getJobName();
                onChanged();
                return this;
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            public Builder setJobNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                jobName_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:RestQueryTaskCriticalPathRequest)
        }

        static {
            defaultInstance = new RestQueryTaskCriticalPathRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:RestQueryTaskCriticalPathRequest)
    }

    public interface ServerQueryTaskCriticalPathResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ServerQueryTaskCriticalPathResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bool success = 1;</code>
         */
        boolean hasSuccess();

        /**
         * <code>required bool success = 1;</code>
         */
        boolean getSuccess();

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        java.util.List<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry> getTaskInfoList();

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry getTaskInfo(int index);

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        int getTaskInfoCount();

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        java.util.List<? extends com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder> getTaskInfoOrBuilderList();

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder getTaskInfoOrBuilder(int index);

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        boolean hasMessage();

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        java.lang.String getMessage();

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        com.google.protobuf.ByteString getMessageBytes();
    }

    /**
     * Protobuf type {@code ServerQueryTaskCriticalPathResponse}
     */
    public static final class ServerQueryTaskCriticalPathResponse extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:ServerQueryTaskCriticalPathResponse)
            ServerQueryTaskCriticalPathResponseOrBuilder {
        // Use ServerQueryTaskCriticalPathResponse.newBuilder() to construct.
        private ServerQueryTaskCriticalPathResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private ServerQueryTaskCriticalPathResponse(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final ServerQueryTaskCriticalPathResponse defaultInstance;

        public static ServerQueryTaskCriticalPathResponse getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public ServerQueryTaskCriticalPathResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private ServerQueryTaskCriticalPathResponse(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            success_ = input.readBool();
                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                taskInfo_ = new java.util.ArrayList<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            taskInfo_.add(input.readMessage(com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.PARSER, extensionRegistry));
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            message_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    taskInfo_ = java.util.Collections.unmodifiableList(taskInfo_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_ServerQueryTaskCriticalPathResponse_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_ServerQueryTaskCriticalPathResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse.class,
                            com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse.Builder.class);
        }

        public static com.google.protobuf.Parser<ServerQueryTaskCriticalPathResponse> PARSER = new com.google.protobuf.AbstractParser<ServerQueryTaskCriticalPathResponse>() {
            @Override
            public ServerQueryTaskCriticalPathResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new ServerQueryTaskCriticalPathResponse(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<ServerQueryTaskCriticalPathResponse> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int SUCCESS_FIELD_NUMBER = 1;
        private boolean success_;

        /**
         * <code>required bool success = 1;</code>
         */
        @Override
        public boolean hasSuccess() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bool success = 1;</code>
         */
        @Override
        public boolean getSuccess() {
            return success_;
        }

        public static final int TASKINFO_FIELD_NUMBER = 2;
        private java.util.List<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry> taskInfo_;

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        @Override
        public java.util.List<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry> getTaskInfoList() {
            return taskInfo_;
        }

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        @Override
        public java.util.List<? extends com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder> getTaskInfoOrBuilderList() {
            return taskInfo_;
        }

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        @Override
        public int getTaskInfoCount() {
            return taskInfo_.size();
        }

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        @Override
        public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry getTaskInfo(int index) {
            return taskInfo_.get(index);
        }

        /**
         * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
         */
        @Override
        public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder getTaskInfoOrBuilder(int index) {
            return taskInfo_.get(index);
        }

        public static final int MESSAGE_FIELD_NUMBER = 3;
        private java.lang.Object message_;

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        @Override
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        @Override
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string message = 3 [default = ""];</code>
         */
        @Override
        public com.google.protobuf.ByteString getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            success_ = false;
            taskInfo_ = java.util.Collections.emptyList();
            message_ = "";
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasSuccess()) {
                memoizedIsInitialized = 0;
                return false;
            }
            for (int i = 0; i < getTaskInfoCount(); i++) {
                if (!getTaskInfo(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBool(1, success_);
            }
            for (int i = 0; i < taskInfo_.size(); i++) {
                output.writeMessage(2, taskInfo_.get(i));
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(3, getMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(1, success_);
            }
            for (int i = 0; i < taskInfo_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, taskInfo_.get(i));
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ServerQueryTaskCriticalPathResponse}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ServerQueryTaskCriticalPathResponse)
                com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_ServerQueryTaskCriticalPathResponse_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_ServerQueryTaskCriticalPathResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse.class,
                                com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse.Builder.class);
            }

            // Construct using com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getTaskInfoFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                success_ = false;
                bitField0_ = (bitField0_ & ~0x00000001);
                if (taskInfoBuilder_ == null) {
                    taskInfo_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    taskInfoBuilder_.clear();
                }
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.internal_static_ServerQueryTaskCriticalPathResponse_descriptor;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse.getDefaultInstance();
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse build() {
                com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse buildPartial() {
                com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse result = new com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.success_ = success_;
                if (taskInfoBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        taskInfo_ = java.util.Collections.unmodifiableList(taskInfo_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.taskInfo_ = taskInfo_;
                } else {
                    result.taskInfo_ = taskInfoBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse) {
                    return mergeFrom((com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse other) {
                if (other == com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse.getDefaultInstance())
                    return this;
                if (other.hasSuccess()) {
                    setSuccess(other.getSuccess());
                }
                if (taskInfoBuilder_ == null) {
                    if (!other.taskInfo_.isEmpty()) {
                        if (taskInfo_.isEmpty()) {
                            taskInfo_ = other.taskInfo_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureTaskInfoIsMutable();
                            taskInfo_.addAll(other.taskInfo_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.taskInfo_.isEmpty()) {
                        if (taskInfoBuilder_.isEmpty()) {
                            taskInfoBuilder_.dispose();
                            taskInfoBuilder_ = null;
                            taskInfo_ = other.taskInfo_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                            taskInfoBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getTaskInfoFieldBuilder() : null;
                        } else {
                            taskInfoBuilder_.addAllMessages(other.taskInfo_);
                        }
                    }
                }
                if (other.hasMessage()) {
                    bitField0_ |= 0x00000004;
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasSuccess()) {

                    return false;
                }
                for (int i = 0; i < getTaskInfoCount(); i++) {
                    if (!getTaskInfo(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.QueryTaskProtos.ServerQueryTaskCriticalPathResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private boolean success_;

            /**
             * <code>required bool success = 1;</code>
             */
            @Override
            public boolean hasSuccess() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bool success = 1;</code>
             */
            @Override
            public boolean getSuccess() {
                return success_;
            }

            /**
             * <code>required bool success = 1;</code>
             */
            public Builder setSuccess(boolean value) {
                bitField0_ |= 0x00000001;
                success_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bool success = 1;</code>
             */
            public Builder clearSuccess() {
                bitField0_ = (bitField0_ & ~0x00000001);
                success_ = false;
                onChanged();
                return this;
            }

            private java.util.List<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry> taskInfo_ = java.util.Collections.emptyList();

            private void ensureTaskInfoIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    taskInfo_ = new java.util.ArrayList<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry>(taskInfo_);
                    bitField0_ |= 0x00000002;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder> taskInfoBuilder_;

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            @Override
            public java.util.List<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry> getTaskInfoList() {
                if (taskInfoBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(taskInfo_);
                } else {
                    return taskInfoBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            @Override
            public int getTaskInfoCount() {
                if (taskInfoBuilder_ == null) {
                    return taskInfo_.size();
                } else {
                    return taskInfoBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            @Override
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry getTaskInfo(int index) {
                if (taskInfoBuilder_ == null) {
                    return taskInfo_.get(index);
                } else {
                    return taskInfoBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder setTaskInfo(int index, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry value) {
                if (taskInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTaskInfoIsMutable();
                    taskInfo_.set(index, value);
                    onChanged();
                } else {
                    taskInfoBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder setTaskInfo(int index, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder builderForValue) {
                if (taskInfoBuilder_ == null) {
                    ensureTaskInfoIsMutable();
                    taskInfo_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    taskInfoBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder addTaskInfo(com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry value) {
                if (taskInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTaskInfoIsMutable();
                    taskInfo_.add(value);
                    onChanged();
                } else {
                    taskInfoBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder addTaskInfo(int index, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry value) {
                if (taskInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTaskInfoIsMutable();
                    taskInfo_.add(index, value);
                    onChanged();
                } else {
                    taskInfoBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder addTaskInfo(com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder builderForValue) {
                if (taskInfoBuilder_ == null) {
                    ensureTaskInfoIsMutable();
                    taskInfo_.add(builderForValue.build());
                    onChanged();
                } else {
                    taskInfoBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder addTaskInfo(int index, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder builderForValue) {
                if (taskInfoBuilder_ == null) {
                    ensureTaskInfoIsMutable();
                    taskInfo_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    taskInfoBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder addAllTaskInfo(java.lang.Iterable<? extends com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry> values) {
                if (taskInfoBuilder_ == null) {
                    ensureTaskInfoIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, taskInfo_);
                    onChanged();
                } else {
                    taskInfoBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder clearTaskInfo() {
                if (taskInfoBuilder_ == null) {
                    taskInfo_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    taskInfoBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public Builder removeTaskInfo(int index) {
                if (taskInfoBuilder_ == null) {
                    ensureTaskInfoIsMutable();
                    taskInfo_.remove(index);
                    onChanged();
                } else {
                    taskInfoBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder getTaskInfoBuilder(int index) {
                return getTaskInfoFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            @Override
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder getTaskInfoOrBuilder(int index) {
                if (taskInfoBuilder_ == null) {
                    return taskInfo_.get(index);
                } else {
                    return taskInfoBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            @Override
            public java.util.List<? extends com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder> getTaskInfoOrBuilderList() {
                if (taskInfoBuilder_ != null) {
                    return taskInfoBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(taskInfo_);
                }
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder addTaskInfoBuilder() {
                return getTaskInfoFieldBuilder().addBuilder(com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.getDefaultInstance());
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder addTaskInfoBuilder(int index) {
                return getTaskInfoFieldBuilder().addBuilder(index,
                        com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.getDefaultInstance());
            }

            /**
             * <code>repeated .TaskInfoEntry taskInfo = 2;</code>
             */
            public java.util.List<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder> getTaskInfoBuilderList() {
                return getTaskInfoFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder> getTaskInfoFieldBuilder() {
                if (taskInfoBuilder_ == null) {
                    taskInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder, com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder>(
                            taskInfo_, ((bitField0_ & 0x00000002) == 0x00000002), getParentForChildren(), isClean());
                    taskInfo_ = null;
                }
                return taskInfoBuilder_;
            }

            private java.lang.Object message_ = "";

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            @Override
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            @Override
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        message_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            @Override
            public com.google.protobuf.ByteString getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            public Builder setMessage(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000004);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 3 [default = ""];</code>
             */
            public Builder setMessageBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ServerQueryTaskCriticalPathResponse)
        }

        static {
            defaultInstance = new ServerQueryTaskCriticalPathResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:ServerQueryTaskCriticalPathResponse)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_RestQueryTaskCriticalPathRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_RestQueryTaskCriticalPathRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_ServerQueryTaskCriticalPathResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_ServerQueryTaskCriticalPathResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\020query_task.proto\032\016app_auth.proto\032\025task"
                + "_info_entry.proto\"c\n RestQueryTaskCritic" + "alPathRequest\022\032\n\010app_auth\030\001 \002(\0132\010.AppAut"
                + "h\022\021\n\tdate_time\030\002 \002(\003\022\020\n\010job_name\030\003 \002(\t\"k"
                + "\n#ServerQueryTaskCriticalPathResponse\022\017\n" + "\007success\030\001 \002(\010\022 \n\010taskInfo\030\002 \003(\0132\016.TaskI"
                + "nfoEntry\022\021\n\007message\030\003 \001(\t:\000B.\n\033com.moguj" + "ie.jarvis.protocolB\017QueryTaskProtos" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            @Override
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] { com.mogujie.jarvis.protocol.AppAuthProtos.getDescriptor(),
                        com.mogujie.jarvis.protocol.TaskInfoEntryProtos.getDescriptor(), },
                assigner);
        internal_static_RestQueryTaskCriticalPathRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_RestQueryTaskCriticalPathRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_RestQueryTaskCriticalPathRequest_descriptor, new java.lang.String[] { "AppAuth", "DateTime", "JobName", });
        internal_static_ServerQueryTaskCriticalPathResponse_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_ServerQueryTaskCriticalPathResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ServerQueryTaskCriticalPathResponse_descriptor, new java.lang.String[] { "Success", "TaskInfo", "Message", });
        com.mogujie.jarvis.protocol.AppAuthProtos.getDescriptor();
        com.mogujie.jarvis.protocol.TaskInfoEntryProtos.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
