// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_info_entry.proto

package com.mogujie.jarvis.protocol;

public final class TaskInfoEntryProtos {
    private TaskInfoEntryProtos() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface TaskInfoEntryOrBuilder extends
            // @@protoc_insertion_point(interface_extends:TaskInfoEntry)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int64 task_id = 1;</code>
         */
        boolean hasTaskId();

        /**
         * <code>required int64 task_id = 1;</code>
         */
        long getTaskId();

        /**
         * <code>required int64 job_id = 2;</code>
         */
        boolean hasJobId();

        /**
         * <code>required int64 job_id = 2;</code>
         */
        long getJobId();

        /**
         * <code>required string job_name = 3;</code>
         */
        boolean hasJobName();

        /**
         * <code>required string job_name = 3;</code>
         */
        java.lang.String getJobName();

        /**
         * <code>required string job_name = 3;</code>
         */
        com.google.protobuf.ByteString getJobNameBytes();

        /**
         * <code>required int64 scheduleTime = 4;</code>
         */
        boolean hasScheduleTime();

        /**
         * <code>required int64 scheduleTime = 4;</code>
         */
        long getScheduleTime();

        /**
         * <code>required int64 dataTime = 5;</code>
         */
        boolean hasDataTime();

        /**
         * <code>required int64 dataTime = 5;</code>
         */
        long getDataTime();

        /**
         * <code>required int64 startTime = 6;</code>
         */
        boolean hasStartTime();

        /**
         * <code>required int64 startTime = 6;</code>
         */
        long getStartTime();

        /**
         * <code>required int64 endTime = 7;</code>
         */
        boolean hasEndTime();

        /**
         * <code>required int64 endTime = 7;</code>
         */
        long getEndTime();

        /**
         * <code>required float avgTime = 8;</code>
         */
        boolean hasAvgTime();

        /**
         * <code>required float avgTime = 8;</code>
         */
        float getAvgTime();

        /**
         * <code>required float useTime = 9;</code>
         */
        boolean hasUseTime();

        /**
         * <code>required float useTime = 9;</code>
         */
        float getUseTime();

        /**
         * <code>required int32 status = 10;</code>
         */
        boolean hasStatus();

        /**
         * <code>required int32 status = 10;</code>
         */
        int getStatus();
    }

    /**
     * Protobuf type {@code TaskInfoEntry}
     */
    public static final class TaskInfoEntry extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:TaskInfoEntry)
            TaskInfoEntryOrBuilder {
        // Use TaskInfoEntry.newBuilder() to construct.
        private TaskInfoEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private TaskInfoEntry(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final TaskInfoEntry defaultInstance;

        public static TaskInfoEntry getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public TaskInfoEntry getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private TaskInfoEntry(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            taskId_ = input.readInt64();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            jobId_ = input.readInt64();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            jobName_ = bs;
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            scheduleTime_ = input.readInt64();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            dataTime_ = input.readInt64();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            startTime_ = input.readInt64();
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000040;
                            endTime_ = input.readInt64();
                            break;
                        }
                        case 69: {
                            bitField0_ |= 0x00000080;
                            avgTime_ = input.readFloat();
                            break;
                        }
                        case 77: {
                            bitField0_ |= 0x00000100;
                            useTime_ = input.readFloat();
                            break;
                        }
                        case 80: {
                            bitField0_ |= 0x00000200;
                            status_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.TaskInfoEntryProtos.internal_static_TaskInfoEntry_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.TaskInfoEntryProtos.internal_static_TaskInfoEntry_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.class,
                    com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder.class);
        }

        public static com.google.protobuf.Parser<TaskInfoEntry> PARSER = new com.google.protobuf.AbstractParser<TaskInfoEntry>() {
            @Override
            public TaskInfoEntry parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new TaskInfoEntry(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<TaskInfoEntry> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int TASK_ID_FIELD_NUMBER = 1;
        private long taskId_;

        /**
         * <code>required int64 task_id = 1;</code>
         */
        @Override
        public boolean hasTaskId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 task_id = 1;</code>
         */
        @Override
        public long getTaskId() {
            return taskId_;
        }

        public static final int JOB_ID_FIELD_NUMBER = 2;
        private long jobId_;

        /**
         * <code>required int64 job_id = 2;</code>
         */
        @Override
        public boolean hasJobId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int64 job_id = 2;</code>
         */
        @Override
        public long getJobId() {
            return jobId_;
        }

        public static final int JOB_NAME_FIELD_NUMBER = 3;
        private java.lang.Object jobName_;

        /**
         * <code>required string job_name = 3;</code>
         */
        @Override
        public boolean hasJobName() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string job_name = 3;</code>
         */
        @Override
        public java.lang.String getJobName() {
            java.lang.Object ref = jobName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    jobName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string job_name = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString getJobNameBytes() {
            java.lang.Object ref = jobName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                jobName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SCHEDULETIME_FIELD_NUMBER = 4;
        private long scheduleTime_;

        /**
         * <code>required int64 scheduleTime = 4;</code>
         */
        @Override
        public boolean hasScheduleTime() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required int64 scheduleTime = 4;</code>
         */
        @Override
        public long getScheduleTime() {
            return scheduleTime_;
        }

        public static final int DATATIME_FIELD_NUMBER = 5;
        private long dataTime_;

        /**
         * <code>required int64 dataTime = 5;</code>
         */
        @Override
        public boolean hasDataTime() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>required int64 dataTime = 5;</code>
         */
        @Override
        public long getDataTime() {
            return dataTime_;
        }

        public static final int STARTTIME_FIELD_NUMBER = 6;
        private long startTime_;

        /**
         * <code>required int64 startTime = 6;</code>
         */
        @Override
        public boolean hasStartTime() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        /**
         * <code>required int64 startTime = 6;</code>
         */
        @Override
        public long getStartTime() {
            return startTime_;
        }

        public static final int ENDTIME_FIELD_NUMBER = 7;
        private long endTime_;

        /**
         * <code>required int64 endTime = 7;</code>
         */
        @Override
        public boolean hasEndTime() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        /**
         * <code>required int64 endTime = 7;</code>
         */
        @Override
        public long getEndTime() {
            return endTime_;
        }

        public static final int AVGTIME_FIELD_NUMBER = 8;
        private float avgTime_;

        /**
         * <code>required float avgTime = 8;</code>
         */
        @Override
        public boolean hasAvgTime() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }

        /**
         * <code>required float avgTime = 8;</code>
         */
        @Override
        public float getAvgTime() {
            return avgTime_;
        }

        public static final int USETIME_FIELD_NUMBER = 9;
        private float useTime_;

        /**
         * <code>required float useTime = 9;</code>
         */
        @Override
        public boolean hasUseTime() {
            return ((bitField0_ & 0x00000100) == 0x00000100);
        }

        /**
         * <code>required float useTime = 9;</code>
         */
        @Override
        public float getUseTime() {
            return useTime_;
        }

        public static final int STATUS_FIELD_NUMBER = 10;
        private int status_;

        /**
         * <code>required int32 status = 10;</code>
         */
        @Override
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000200) == 0x00000200);
        }

        /**
         * <code>required int32 status = 10;</code>
         */
        @Override
        public int getStatus() {
            return status_;
        }

        private void initFields() {
            taskId_ = 0L;
            jobId_ = 0L;
            jobName_ = "";
            scheduleTime_ = 0L;
            dataTime_ = 0L;
            startTime_ = 0L;
            endTime_ = 0L;
            avgTime_ = 0F;
            useTime_ = 0F;
            status_ = 0;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasTaskId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasJobId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasJobName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasScheduleTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDataTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasStartTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasEndTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAvgTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasUseTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasStatus()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, taskId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, jobId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getJobNameBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt64(4, scheduleTime_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt64(5, dataTime_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeInt64(6, startTime_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeInt64(7, endTime_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeFloat(8, avgTime_);
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                output.writeFloat(9, useTime_);
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                output.writeInt32(10, status_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, taskId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, jobId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getJobNameBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, scheduleTime_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(5, dataTime_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(6, startTime_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(7, endTime_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream.computeFloatSize(8, avgTime_);
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                size += com.google.protobuf.CodedOutputStream.computeFloatSize(9, useTime_);
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(10, status_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code TaskInfoEntry}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:TaskInfoEntry)
                com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.TaskInfoEntryProtos.internal_static_TaskInfoEntry_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.TaskInfoEntryProtos.internal_static_TaskInfoEntry_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.class,
                                com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.Builder.class);
            }

            // Construct using com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                taskId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                jobId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                jobName_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                scheduleTime_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000008);
                dataTime_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000010);
                startTime_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000020);
                endTime_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000040);
                avgTime_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000080);
                useTime_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000100);
                status_ = 0;
                bitField0_ = (bitField0_ & ~0x00000200);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.TaskInfoEntryProtos.internal_static_TaskInfoEntry_descriptor;
            }

            @Override
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.getDefaultInstance();
            }

            @Override
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry build() {
                com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry buildPartial() {
                com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry result = new com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.taskId_ = taskId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.jobId_ = jobId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.jobName_ = jobName_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.scheduleTime_ = scheduleTime_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.dataTime_ = dataTime_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.startTime_ = startTime_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.endTime_ = endTime_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.avgTime_ = avgTime_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000100;
                }
                result.useTime_ = useTime_;
                if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
                    to_bitField0_ |= 0x00000200;
                }
                result.status_ = status_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry) {
                    return mergeFrom((com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry other) {
                if (other == com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry.getDefaultInstance())
                    return this;
                if (other.hasTaskId()) {
                    setTaskId(other.getTaskId());
                }
                if (other.hasJobId()) {
                    setJobId(other.getJobId());
                }
                if (other.hasJobName()) {
                    bitField0_ |= 0x00000004;
                    jobName_ = other.jobName_;
                    onChanged();
                }
                if (other.hasScheduleTime()) {
                    setScheduleTime(other.getScheduleTime());
                }
                if (other.hasDataTime()) {
                    setDataTime(other.getDataTime());
                }
                if (other.hasStartTime()) {
                    setStartTime(other.getStartTime());
                }
                if (other.hasEndTime()) {
                    setEndTime(other.getEndTime());
                }
                if (other.hasAvgTime()) {
                    setAvgTime(other.getAvgTime());
                }
                if (other.hasUseTime()) {
                    setUseTime(other.getUseTime());
                }
                if (other.hasStatus()) {
                    setStatus(other.getStatus());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasTaskId()) {

                    return false;
                }
                if (!hasJobId()) {

                    return false;
                }
                if (!hasJobName()) {

                    return false;
                }
                if (!hasScheduleTime()) {

                    return false;
                }
                if (!hasDataTime()) {

                    return false;
                }
                if (!hasStartTime()) {

                    return false;
                }
                if (!hasEndTime()) {

                    return false;
                }
                if (!hasAvgTime()) {

                    return false;
                }
                if (!hasUseTime()) {

                    return false;
                }
                if (!hasStatus()) {

                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.TaskInfoEntryProtos.TaskInfoEntry) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private long taskId_;

            /**
             * <code>required int64 task_id = 1;</code>
             */
            @Override
            public boolean hasTaskId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int64 task_id = 1;</code>
             */
            @Override
            public long getTaskId() {
                return taskId_;
            }

            /**
             * <code>required int64 task_id = 1;</code>
             */
            public Builder setTaskId(long value) {
                bitField0_ |= 0x00000001;
                taskId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 task_id = 1;</code>
             */
            public Builder clearTaskId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                taskId_ = 0L;
                onChanged();
                return this;
            }

            private long jobId_;

            /**
             * <code>required int64 job_id = 2;</code>
             */
            @Override
            public boolean hasJobId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int64 job_id = 2;</code>
             */
            @Override
            public long getJobId() {
                return jobId_;
            }

            /**
             * <code>required int64 job_id = 2;</code>
             */
            public Builder setJobId(long value) {
                bitField0_ |= 0x00000002;
                jobId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 job_id = 2;</code>
             */
            public Builder clearJobId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                jobId_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object jobName_ = "";

            /**
             * <code>required string job_name = 3;</code>
             */
            @Override
            public boolean hasJobName() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            @Override
            public java.lang.String getJobName() {
                java.lang.Object ref = jobName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        jobName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            @Override
            public com.google.protobuf.ByteString getJobNameBytes() {
                java.lang.Object ref = jobName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    jobName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            public Builder setJobName(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                jobName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            public Builder clearJobName() {
                bitField0_ = (bitField0_ & ~0x00000004);
                jobName_ = getDefaultInstance().getJobName();
                onChanged();
                return this;
            }

            /**
             * <code>required string job_name = 3;</code>
             */
            public Builder setJobNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                jobName_ = value;
                onChanged();
                return this;
            }

            private long scheduleTime_;

            /**
             * <code>required int64 scheduleTime = 4;</code>
             */
            @Override
            public boolean hasScheduleTime() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>required int64 scheduleTime = 4;</code>
             */
            @Override
            public long getScheduleTime() {
                return scheduleTime_;
            }

            /**
             * <code>required int64 scheduleTime = 4;</code>
             */
            public Builder setScheduleTime(long value) {
                bitField0_ |= 0x00000008;
                scheduleTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 scheduleTime = 4;</code>
             */
            public Builder clearScheduleTime() {
                bitField0_ = (bitField0_ & ~0x00000008);
                scheduleTime_ = 0L;
                onChanged();
                return this;
            }

            private long dataTime_;

            /**
             * <code>required int64 dataTime = 5;</code>
             */
            @Override
            public boolean hasDataTime() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>required int64 dataTime = 5;</code>
             */
            @Override
            public long getDataTime() {
                return dataTime_;
            }

            /**
             * <code>required int64 dataTime = 5;</code>
             */
            public Builder setDataTime(long value) {
                bitField0_ |= 0x00000010;
                dataTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 dataTime = 5;</code>
             */
            public Builder clearDataTime() {
                bitField0_ = (bitField0_ & ~0x00000010);
                dataTime_ = 0L;
                onChanged();
                return this;
            }

            private long startTime_;

            /**
             * <code>required int64 startTime = 6;</code>
             */
            @Override
            public boolean hasStartTime() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>required int64 startTime = 6;</code>
             */
            @Override
            public long getStartTime() {
                return startTime_;
            }

            /**
             * <code>required int64 startTime = 6;</code>
             */
            public Builder setStartTime(long value) {
                bitField0_ |= 0x00000020;
                startTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 startTime = 6;</code>
             */
            public Builder clearStartTime() {
                bitField0_ = (bitField0_ & ~0x00000020);
                startTime_ = 0L;
                onChanged();
                return this;
            }

            private long endTime_;

            /**
             * <code>required int64 endTime = 7;</code>
             */
            @Override
            public boolean hasEndTime() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            /**
             * <code>required int64 endTime = 7;</code>
             */
            @Override
            public long getEndTime() {
                return endTime_;
            }

            /**
             * <code>required int64 endTime = 7;</code>
             */
            public Builder setEndTime(long value) {
                bitField0_ |= 0x00000040;
                endTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 endTime = 7;</code>
             */
            public Builder clearEndTime() {
                bitField0_ = (bitField0_ & ~0x00000040);
                endTime_ = 0L;
                onChanged();
                return this;
            }

            private float avgTime_;

            /**
             * <code>required float avgTime = 8;</code>
             */
            @Override
            public boolean hasAvgTime() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }

            /**
             * <code>required float avgTime = 8;</code>
             */
            @Override
            public float getAvgTime() {
                return avgTime_;
            }

            /**
             * <code>required float avgTime = 8;</code>
             */
            public Builder setAvgTime(float value) {
                bitField0_ |= 0x00000080;
                avgTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required float avgTime = 8;</code>
             */
            public Builder clearAvgTime() {
                bitField0_ = (bitField0_ & ~0x00000080);
                avgTime_ = 0F;
                onChanged();
                return this;
            }

            private float useTime_;

            /**
             * <code>required float useTime = 9;</code>
             */
            @Override
            public boolean hasUseTime() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }

            /**
             * <code>required float useTime = 9;</code>
             */
            @Override
            public float getUseTime() {
                return useTime_;
            }

            /**
             * <code>required float useTime = 9;</code>
             */
            public Builder setUseTime(float value) {
                bitField0_ |= 0x00000100;
                useTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required float useTime = 9;</code>
             */
            public Builder clearUseTime() {
                bitField0_ = (bitField0_ & ~0x00000100);
                useTime_ = 0F;
                onChanged();
                return this;
            }

            private int status_;

            /**
             * <code>required int32 status = 10;</code>
             */
            @Override
            public boolean hasStatus() {
                return ((bitField0_ & 0x00000200) == 0x00000200);
            }

            /**
             * <code>required int32 status = 10;</code>
             */
            @Override
            public int getStatus() {
                return status_;
            }

            /**
             * <code>required int32 status = 10;</code>
             */
            public Builder setStatus(int value) {
                bitField0_ |= 0x00000200;
                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 status = 10;</code>
             */
            public Builder clearStatus() {
                bitField0_ = (bitField0_ & ~0x00000200);
                status_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:TaskInfoEntry)
        }

        static {
            defaultInstance = new TaskInfoEntry(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:TaskInfoEntry)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_TaskInfoEntry_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_TaskInfoEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\025task_info_entry.proto\"\300\001\n\rTaskInfoEntr"
                + "y\022\017\n\007task_id\030\001 \002(\003\022\016\n\006job_id\030\002 \002(\003\022\020\n\010jo"
                + "b_name\030\003 \002(\t\022\024\n\014scheduleTime\030\004 \002(\003\022\020\n\010da"
                + "taTime\030\005 \002(\003\022\021\n\tstartTime\030\006 \002(\003\022\017\n\007endTi"
                + "me\030\007 \002(\003\022\017\n\007avgTime\030\010 \002(\002\022\017\n\007useTime\030\t \002"
                + "(\002\022\016\n\006status\030\n \002(\005B2\n\033com.mogujie.jarvis" + ".protocolB\023TaskInfoEntryProtos" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            @Override
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_TaskInfoEntry_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_TaskInfoEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_TaskInfoEntry_descriptor, new java.lang.String[] { "TaskId", "JobId", "JobName", "ScheduleTime", "DataTime",
                        "StartTime", "EndTime", "AvgTime", "UseTime", "Status", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
